[package]
name = "alpino-tokenize"
version = "0.1.0"
authors = ["Daniël de Kok <me@danieldk.eu>"]
edition = "2018"

[dependencies]
alpino-tokenizer = { path = "../alpino-tokenizer", version = "0.1.0" }
clap = "2"
conllx = "0.12"
stdinout = "0.4"