[package]
name = "alpino-tokenizer-sys"
version = "0.1.0"
authors = ["Daniël de Kok <me@danieldk.eu>"]
edition = "2018"

[build-dependencies]
cc = "1"

[dependencies]
widestring = "0.4"

[dev-dependencies]
libc = "0.2"